### ISSUE TITLE
Add support in PDC.configure defer fetching of token to first request.

### ISSUE THREAD

**Issue by sthaha** [product-definition-center/pdc-ruby-gem#7]
Currently `PDC.configure` fetches token immediately. This adds a constraint on the order of initialisation i.e that a ticket must be present before invoking `configure`. Additionally, the token is fetched even if a
call to pdc may not take place.

The proposal is to add support so that  `PDC.configure` only stores the configuration. The token can be
fetched at  a later point (when the first call to the server is made) instead of fetching it immediately on configure.

Doing this allows separation of  configuration of PDC from initialisation (fetch token).

**Comment by sthaha** [comment]
A solution to the above may be to add a faraday middleware that fetches token once, stores it, and inserts the token as header.

**Comment by ycheng-aa** [comment]
Resolved in https://github.com/product-definition-center/pdc-ruby-gem/pull/12.
